const config = require("../config");
const {getUser} = require("../database/db");

const PREFIX = config.prefix;

const mainMenuButton = [
  {
    name: "single_select",
    buttonParamsJson: JSON.stringify({
      title: "PILIH KATEGORI MENU",
      sections: [
        {
          title: "─── [ ℹ️ INFORMASI ] ───",
          rows: [
            {title: `${PREFIX}owner`, id: `${PREFIX}owner`, description: "Informasi mengenai pemilik bot ini"},
            {title: `${PREFIX}profil`, id: `${PREFIX}profil`, description: "Lihat data statistik profil Anda"},
            {title: `${PREFIX}cuaca`, id: `${PREFIX}cuaca`, description: "Cek kondisi cuaca di lokasi Anda"},
            {title: `${PREFIX}cuacaalert`, id: `${PREFIX}cuacaalert`, description: "Peringatan cuaca ekstrem terbaru"},
            {title: `${PREFIX}gempa`, id: `${PREFIX}gempa`, description: "Update gempa bumi terkini dari BMKG"},
          ],
        },
        {
          title: "─── [ 🔍 SEARCH ENGINE ] ───",
          rows: [
            {title: `${PREFIX}kbbi`, id: `${PREFIX}kbbi`, description: "Cari definisi kata dalam Bahasa Indonesia"},
            {title: `${PREFIX}wiki`, id: `${PREFIX}wiki`, description: "Cari informasi di ensiklopedia bebas"},
            {title: `${PREFIX}slang`, id: `${PREFIX}slang`, description: "Cari arti kata gaul/slang masa kini"},
            {title: `${PREFIX}arti`, id: `${PREFIX}arti`, description: "Cari makna dari suatu istilah atau kata"},
            {title: `${PREFIX}singkatan`, id: `${PREFIX}singkatan`, description: "Cari kepanjangan dari suatu singkatan"},
            {title: `${PREFIX}lirik`, id: `${PREFIX}lirik`, description: "Cari lirik lagu favorit Anda"},
            {title: `${PREFIX}pinterest`, id: `${PREFIX}pinterest`, description: "Cari inspirasi gambar di Pinterest"},
            {title: `${PREFIX}yaho`, id: `${PREFIX}yaho`, description: "Cari konten video menarik"},
            {title: `${PREFIX}lahelu`, id: `${PREFIX}lahelu`, description: "Cari meme lucu di platform Lahelu"},
          ],
        },
        {
          title: "─── [ 👥 GRUP MANAGER ] ───",
          rows: [
            {title: `${PREFIX}setwelcome`, id: `${PREFIX}setwelcome`, description: "Atur pesan sambutan anggota baru"},
            {title: `${PREFIX}setleave`, id: `${PREFIX}setleave`, description: "Atur pesan perpisahan anggota keluar"},
            {title: `${PREFIX}promote`, id: `${PREFIX}promote`, description: "Jadikan anggota sebagai admin grup"},
            {title: `${PREFIX}demote`, id: `${PREFIX}demote`, description: "Hapus jabatan admin anggota"},
            {title: `${PREFIX}kick`, id: `${PREFIX}kick`, description: "Keluarkan anggota dari dalam grup"},
            {title: `${PREFIX}tagall`, id: `${PREFIX}tagall`, description: "Tag seluruh anggota grup sekaligus"},
            {title: `${PREFIX}hidetag`, id: `${PREFIX}hidetag`, description: "Tag seluruh anggota tanpa terlihat"},
            {title: `${PREFIX}groupinfo`, id: `${PREFIX}groupinfo`, description: "Lihat informasi lengkap grup ini"},
            {title: `${PREFIX}linkgroup`, id: `${PREFIX}linkgroup`, description: "Ambil link undangan grup ini"},
            {title: `${PREFIX}warn`, id: `${PREFIX}warn`, description: "Beri peringatan kepada pelanggar"},
            {title: `${PREFIX}antilink`, id: `${PREFIX}antilink`, description: "Aktifkan perlindungan link otomatis"},
            {title: `${PREFIX}setdesc`, id: `${PREFIX}setdesc`, description: "Ubah deskripsi informasi grup"},
          ],
        },
        {
          title: "─── [ 🎮 MINIGAMES ] ───",
          rows: [
            {title: `${PREFIX}tebakkata`, id: `${PREFIX}tebakkata`, description: "Uji kemampuan kosakata Anda"},
            {title: `${PREFIX}kuis`, id: `${PREFIX}kuis`, description: "Jawab kuis pengetahuan umum"},
            {title: `${PREFIX}tebakgambar`, id: `${PREFIX}tebakgambar`, description: "Tebak kata dari gambar yang muncul"},
            {title: `${PREFIX}spin`, id: `${PREFIX}spin`, description: "Pilih sesuatu secara acak dari daftar"},
            {title: `${PREFIX}blackjack`, id: `${PREFIX}blackjack`, description: "Mainkan Blackjack multiplayer dengan taruhan"},
          ],
        },
        {
          title: "─── [ 🕋 ISLAMI ] ───",
          rows: [
            {title: `${PREFIX}sholat`, id: `${PREFIX}sholat`, description: "Cek waktu sholat di wilayah Anda"},
            {title: `${PREFIX}quran`, id: `${PREFIX}quran`, description: "Baca ayat suci Al-Quran & terjemahan"},
          ],
        },
        {
          title: "─── [ 🛠️ TOOLS & EDIT ] ───",
          rows: [
            {title: `${PREFIX}sticker`, id: `${PREFIX}sticker`, description: "Ubah gambar menjadi stiker WhatsApp"},
            {title: `${PREFIX}removebg`, id: `${PREFIX}removebg`, description: "Hapus latar belakang foto otomatis"},
            {title: `${PREFIX}tts`, id: `${PREFIX}tts`, description: "Ubah teks menjadi pesan suara"},
            {title: `${PREFIX}kalkulator`, id: `${PREFIX}kalkulator`, description: "Hitung matematika dengan cepat"},
            {title: `${PREFIX}qr generate`, id: `${PREFIX}qr generate`, description: "Buat kode QR sesuai keinginan"},
            {title: `${PREFIX}qr scan`, id: `${PREFIX}qr scan`, description: "Scan kode QR dari gambar"},
            {title: `${PREFIX}toimg`, id: `${PREFIX}toimg`, description: "Ubah stiker kembali menjadi gambar"},
            {title: `${PREFIX}unblur`, id: `${PREFIX}unblur`, description: "Pertajam foto yang buram/blur"},
            {title: `${PREFIX}remini`, id: `${PREFIX}remini`, description: "Tingkatkan kualitas foto menjadi HD"},
            {title: `${PREFIX}colorize`, id: `${PREFIX}colorize`, description: "Warnai foto hitam putih jadul"},
            {title: `${PREFIX}smeme`, id: `${PREFIX}smeme`, description: "Buat stiker meme dengan teks"},
          ],
        },
        {
          title: "─── [ 🎬 ANIME HUB ] ───",
          rows: [
            {title: `${PREFIX}otakudesu`, id: `${PREFIX}otakudesu`, description: "Cari, detail, dan tonton anime terbaru"},
            {title: `${PREFIX}donghua`, id: `${PREFIX}donghua`, description: "Cari dan tonton donghua favorit"},
            {title: `${PREFIX}novel`, id: `${PREFIX}novel`, description: "Cari dan baca novel secara online"},
            {title: `${PREFIX}tracemoe`, id: `${PREFIX}tracemoe`, description: "Cari judul anime dari cuplikan gambar"},
          ],
        },
        {
          title: "─── [ 🤖 AI ASSISTANT ] ───",
          rows: [
            {title: `${PREFIX}tr`, id: `${PREFIX}tr`, description: "Terjemahkan bahasa antar negara"},
            {title: `${PREFIX}summarize`, id: `${PREFIX}summarize`, description: "Ringkas dokumen/teks panjang"},
            {title: `${PREFIX}paraphrase`, id: `${PREFIX}paraphrase`, description: "Ubah susunan kalimat teks"},
            {title: `${PREFIX}expand`, id: `${PREFIX}expand`, description: "Perluas ide dari teks singkat"},
            {title: `${PREFIX}grammar`, id: `${PREFIX}grammar`, description: "Perbaiki tata bahasa tulisan"},
            {title: `${PREFIX}dracintts`, id: `${PREFIX}dracintts`, description: "TTS dengan suara khas drama china"},
            {title: `${PREFIX}geminiai`, id: `${PREFIX}geminiai`, description: "Tanya apa saja ke Google Gemini"},
            {title: `${PREFIX}gptai`, id: `${PREFIX}gptai`, description: "Tanya apa saja ke OpenAI ChatGPT"},
            {title: `${PREFIX}deepseekai`, id: `${PREFIX}deepseekai`, description: "AI pintar untuk analisis mendalam"},
            {title: `${PREFIX}quillbot`, id: `${PREFIX}quillbot`, description: "Tulis ulang teks secara profesional"},
            {title: `${PREFIX}cerpen`, id: `${PREFIX}cerpen`, description: "Buat cerita pendek dari tema tertentu"},
            {title: `${PREFIX}puisi`, id: `${PREFIX}puisi`, description: "Buat puisi indah dari tema tertentu"},
            {title: `${PREFIX}pantun`, id: `${PREFIX}pantun`, description: "Buat beberapa bait pantun kreatif"},
            {title: `${PREFIX}syair`, id: `${PREFIX}syair`, description: "Buat bait-bait syair yang bermakna"},
          ],
        },
        {
          title: "─── [ 📥 DOWNLOADER ] ───",
          rows: [
            {title: `${PREFIX}tiktok`, id: `${PREFIX}tiktok`, description: "Unduh video TikTok tanpa watermark"},
            {title: `${PREFIX}ig`, id: `${PREFIX}ig`, description: "Unduh video/foto dari Instagram"},
            {title: `${PREFIX}ytmp3`, id: `${PREFIX}ytmp3`, description: "Unduh lagu dari link YouTube"},
            {title: `${PREFIX}ytmp4`, id: `${PREFIX}ytmp4`, description: "Unduh video dari link YouTube"},
            {title: `${PREFIX}fb`, id: `${PREFIX}fb`, description: "Unduh video dari platform Facebook"},
            {title: `${PREFIX}twitter`, id: `${PREFIX}twitter`, description: "Unduh video dari platform X/Twitter"},
            {title: `${PREFIX}spotify`, id: `${PREFIX}spotify`, description: "Unduh lagu dari platform Spotify"},
          ],
        },
        {
          title: "─── [ 🤖 BOT SYSTEM ] ───",
          rows: [
            {title: `${PREFIX}ping`, id: `${PREFIX}ping`, description: "Cek kecepatan respon bot"},
            {title: `${PREFIX}speed`, id: `${PREFIX}speed`, description: "Tes kecepatan server bot"},
            {title: `${PREFIX}runtime`, id: `${PREFIX}runtime`, description: "Cek waktu aktif operasional bot"},
            {title: `${PREFIX}status`, id: `${PREFIX}status`, description: "Lihat statistik sistem bot"},
          ],
        },
        {
          title: "─── [ 👑 OWNER PANEL ] ───",
          rows: [
            {title: `${PREFIX}whitelist`, id: `${PREFIX}whitelist`, description: "Kelola daftar putih bot"},
            {title: `${PREFIX}botmode`, id: `${PREFIX}botmode`, description: "Ubah mode operasional bot"},
            {title: `${PREFIX}restart`, id: `${PREFIX}restart`, description: "Mulai ulang sistem bot"},
            {title: `${PREFIX}shutdown`, id: `${PREFIX}shutdown`, description: "Matikan sistem bot total"},
            {title: `${PREFIX}setprefix`, id: `${PREFIX}setprefix`, description: "Ubah prefix perintah bot"},
            {title: `${PREFIX}maintenance`, id: `${PREFIX}maintenance`, description: "Aktifkan mode perbaikan"},
            {title: `${PREFIX}ban`, id: `${PREFIX}ban`, description: "Blokir akses user ke bot"},
            {title: `${PREFIX}unban`, id: `${PREFIX}unban`, description: "Buka blokir akses user"},
            {title: `${PREFIX}blacklist`, id: `${PREFIX}blacklist`, description: "Kelola daftar hitam bot"},
          ],
        },
      ],
    }),
  },
];

async function sendMenuWithImage(sock, jid, sender, m) {
  const user = getUser(sender);
  const userName = user ? user.name : "User";
  const userAge = user ? `${user.age} tahun` : "-";
  const userSince = user ? new Date(user.registeredAt).toLocaleDateString("id-ID") : "-";
  const time = new Date().toLocaleTimeString("id-ID", { timeZone: "Asia/Jakarta" });
  const date = new Date().toLocaleDateString("id-ID", { timeZone: "Asia/Jakarta" });

  const isGroup = jid.endsWith("@g.us");

  const headerBox = [
    `🚀 *${config.botName.toUpperCase()}* 🌟`,
    `────────────────────`,
    `👋 Halo, *${userName}*!`,
    ``,
    `📅 *DATE:* ${date}`,
    `⌚ *TIME:* ${time} WIB`,
    `────────────────────`,
    `📂 *USER INFO*`,
    `├ 👤 *Nama:* ${userName}`,
    `├ 🎂 *Umur:* ${userAge}`,
    `└ 📅 *Join:* ${userSince}`,
    `────────────────────`,
    `💻 *BOT STATS*`,
    `├ 💠 *Prefix:* [ ${PREFIX} ]`,
    `└ 🛡️ *Status:* Online`,
    `────────────────────`,
  ].join("\n");

  if (isGroup) {
    const body = headerBox + `\n\nSilakan pilih kategori menu melalui tombol di bawah ini untuk melihat daftar perintah selengkapnya!`;

    await sock.sendMessage(jid, {
      interactiveMessage: {
        image: config.botImage,
        title: body,
        footer: `© ${new Date().getFullYear()} ${config.botName} • ${config.ownerName}`,
        buttons: mainMenuButton,
      },
    });
  } else {
    const menuLines = [
      headerBox,
      `📖 *DAFTAR PERINTAH*`,
      ``,
      `┌─ [ ℹ️ *INFORMASI* ]`,
      `│ ◦ *${PREFIX}owner*`,
      `│ ◦ *${PREFIX}profil*`,
      `│ ◦ *${PREFIX}cuaca*`,
      `│ ◦ *${PREFIX}cuacaalert*`,
      `│ ◦ *${PREFIX}gempa*`,
      `└───────────────`,
      ``,
      `┌─ [ 🔍 *SEARCH* ]`,
      `│ ◦ *${PREFIX}kbbi*`,
      `│ ◦ *${PREFIX}wiki*`,
      `│ ◦ *${PREFIX}slang*`,
      `│ ◦ *${PREFIX}arti*`,
      `│ ◦ *${PREFIX}singkatan*`,
      `│ ◦ *${PREFIX}lirik*`,
      `│ ◦ *${PREFIX}pinterest*`,
      `│ ◦ *${PREFIX}yaho*`,
      `│ ◦ *${PREFIX}lahelu*`,
      `└───────────────`,
      ``,
      `┌─ [ 👥 *GRUP* ]`,
      `│ ◦ *${PREFIX}setwelcome*`,
      `│ ◦ *${PREFIX}setleave*`,
      `│ ◦ *${PREFIX}promote*`,
      `│ ◦ *${PREFIX}demote*`,
      `│ ◦ *${PREFIX}kick*`,
      `│ ◦ *${PREFIX}tagall*`,
      `│ ◦ *${PREFIX}hidetag*`,
      `│ ◦ *${PREFIX}groupinfo*`,
      `│ ◦ *${PREFIX}linkgroup*`,
      `│ ◦ *${PREFIX}warn*`,
      `│ ◦ *${PREFIX}antilink*`,
      `│ ◦ *${PREFIX}setdesc*`,
      `└───────────────`,
      ``,
      `┌─ [ 🎮 *MINIGAME* ]`,
      `│ ◦ *${PREFIX}tebakkata*`,
      `│ ◦ *${PREFIX}kuis*`,
      `│ ◦ *${PREFIX}tebakgambar*`,
      `│ ◦ *${PREFIX}spin*`,
      `│ ◦ *${PREFIX}blackjack*`,
      `└───────────────`,
      ``,
      `┌─ [ 🕋 *ISLAMI* ]`,
      `│ ◦ *${PREFIX}sholat*`,
      `│ ◦ *${PREFIX}quran*`,
      `└───────────────`,
      ``,
      `┌─ [ 🛠️ *TOOLS* ]`,
      `│ ◦ *${PREFIX}sticker*`,
      `│ ◦ *${PREFIX}removebg*`,
      `│ ◦ *${PREFIX}tts*`,
      `│ ◦ *${PREFIX}kalkulator*`,
      `│ ◦ *${PREFIX}qr generate*`,
      `│ ◦ *${PREFIX}qr scan*`,
      `│ ◦ *${PREFIX}toimg*`,
      `│ ◦ *${PREFIX}unblur*`,
      `│ ◦ *${PREFIX}remini*`,
      `│ ◦ *${PREFIX}colorize*`,
      `│ ◦ *${PREFIX}smeme*`,
      `└───────────────`,
      ``,
      `┌─ [ 🎬 *ANIME* ]`,
      `│ ◦ *${PREFIX}otakudesu*`,
      `│ ◦ *${PREFIX}donghua*`,
      `│ ◦ *${PREFIX}novel*`,
      `│ ◦ *${PREFIX}tracemoe*`,
      `└───────────────`,
      ``,
      `┌─ [ 🤖 *AI* ]`,
      `│ ◦ *${PREFIX}tr*`,
      `│ ◦ *${PREFIX}summarize*`,
      `│ ◦ *${PREFIX}paraphrase*`,
      `│ ◦ *${PREFIX}expand*`,
      `│ ◦ *${PREFIX}grammar*`,
      `│ ◦ *${PREFIX}dracintts*`,
      `│ ◦ *${PREFIX}geminiai*`,
      `│ ◦ *${PREFIX}gptai*`,
      `│ ◦ *${PREFIX}deepseekai*`,
      `│ ◦ *${PREFIX}quillbot*`,
      `│ ◦ *${PREFIX}cerpen*`,
      `│ ◦ *${PREFIX}puisi*`,
      `│ ◦ *${PREFIX}pantun*`,
      `│ ◦ *${PREFIX}syair*`,
      `└───────────────`,
      ``,
      `┌─ [ 📥 *DOWNLOAD* ]`,
      `│ ◦ *${PREFIX}tiktok*`,
      `│ ◦ *${PREFIX}ig*`,
      `│ ◦ *${PREFIX}ytmp3*`,
      `│ ◦ *${PREFIX}ytmp4*`,
      `│ ◦ *${PREFIX}fb*`,
      `│ ◦ *${PREFIX}twitter*`,
      `│ ◦ *${PREFIX}spotify*`,
      `└───────────────`,
      ``,
      `┌─ [ 👑 *OWNER* ]`,
      `│ ◦ *${PREFIX}whitelist*`,
      `│ ◦ *${PREFIX}botmode*`,
      `│ ◦ *${PREFIX}restart*`,
      `│ ◦ *${PREFIX}shutdown*`,
      `│ ◦ *${PREFIX}setprefix*`,
      `│ ◦ *${PREFIX}maintenance*`,
      `│ ◦ *${PREFIX}ban*`,
      `│ ◦ *${PREFIX}unban*`,
      `│ ◦ *${PREFIX}blacklist*`,
      `└───────────────`,
      ``,
      `© ${new Date().getFullYear()} ${config.botName} • ${config.ownerName}`,
    ].join("\n");

    await sock.sendMessage(jid, { image: config.botImage, caption: menuLines }, { quoted: m });
  }
}

module.exports = {
  mainMenuButton,
  sendMenuWithImage,
};
